[project]
name = "narada-core"
version = "0.1.0"
description = "Core models and actions for Narada"
license = "Apache-2.0"
readme = "README.md"
authors = [{ name = "Narada", email = "support@narada.ai" }]
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.10.6",
]

[project.urls]
Homepage = "https://github.com/NaradaAI/narada-python-sdk/narada-core"
Repository = "https://github.com/NaradaAI/narada-python-sdk"
Issues = "https://github.com/NaradaAI/narada-python-sdk/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/narada_core"]
