from __future__ import annotations

import ast
import base64
import gzip
import json
import os
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path, PurePosixPath
from typing import Any

from narada.workbench import (
    _SECRET_PATTERNS,
    _SELF_REVIEW_PATTERNS,
    _STATIC_ANSWER_PATTERNS,
    _redact_sensitive_text,
    _sha256_bytes,
    _sha256_json,
)

PROJECT_SYNC_GENERATOR = "narada-workbench-sync-python-project"
PROJECT_SYNC_SCHEMA_VERSION = 1
GENERATED_HEADER = "GENERATED BY NARADA WORKBENCH - DO NOT EDIT IN AGENT STUDIO"

ALLOWED_SUFFIXES = frozenset({".py", ".json", ".txt", ".md", ".csv", ".yaml", ".yml"})
EXCLUDED_DIR_NAMES = frozenset(
    {
        ".git",
        ".venv",
        "venv",
        "__pycache__",
        ".pytest_cache",
        ".mypy_cache",
        ".ruff_cache",
        ".narada",
        "node_modules",
        "dist",
        "build",
        "wheels",
        "downloads",
    }
)
EXCLUDED_FILE_NAMES = frozenset(
    {
        ".DS_Store",
        "generated-runtime.py",
    }
)
GENERATED_HEADER_PREFIX = "# " + GENERATED_HEADER
DEFAULT_MAX_FILE_BYTES = 512 * 1024
DEFAULT_MAX_TOTAL_BYTES = 3 * 1024 * 1024


class ProjectSyncError(ValueError):
    pass


@dataclass(frozen=True)
class ProjectFile:
    relative_path: str
    content: str
    content_bytes: bytes
    sha256: str
    size_bytes: int


@dataclass(frozen=True)
class ProjectPackage:
    manifest: dict[str, Any]
    files: list[ProjectFile]
    runtime_code: str
    package_report: dict[str, Any]


def build_project_package(
    *,
    local: str | Path,
    entrypoint: str,
    regeneration_command: str | None = None,
    max_file_bytes: int = DEFAULT_MAX_FILE_BYTES,
    max_total_bytes: int = DEFAULT_MAX_TOTAL_BYTES,
) -> ProjectPackage:
    root = Path(local).expanduser().resolve()
    if not root.exists() or not root.is_dir():
        raise ProjectSyncError("--local must point to an existing directory")
    entrypoint_path = _normalize_relative_path(entrypoint)
    files = _scan_project(
        root,
        max_file_bytes=max_file_bytes,
        max_total_bytes=max_total_bytes,
    )
    files_by_path = {file.relative_path: file for file in files}
    if entrypoint_path not in files_by_path:
        raise ProjectSyncError("Entrypoint must be an included project file")
    if not entrypoint_path.endswith(".py"):
        raise ProjectSyncError("Entrypoint must be a Python file")

    source_manifest = {
        "schemaVersion": PROJECT_SYNC_SCHEMA_VERSION,
        "generator": PROJECT_SYNC_GENERATOR,
        "entrypoint": entrypoint_path,
        "files": [
            {
                "path": file.relative_path,
                "sizeBytes": file.size_bytes,
                "sha256": file.sha256,
            }
            for file in files
        ],
        "sourceTreeSha256": _source_tree_hash(files),
        "runtimeSha256": None,
        "regenerationCommand": _redact_sensitive_text(regeneration_command or ""),
        "generatedAt": _now_iso(),
    }
    bundle = {
        "schemaVersion": PROJECT_SYNC_SCHEMA_VERSION,
        "files": [
            {"path": file.relative_path, "content": file.content} for file in files
        ],
    }
    encoded_bundle = base64.b64encode(
        gzip.compress(
            json.dumps(bundle, sort_keys=True, separators=(",", ":")).encode("utf-8")
        )
    ).decode("ascii")
    runtime_code = _render_runtime_code(source_manifest, encoded_bundle)
    manifest = {
        **source_manifest,
        "runtimeSha256": _sha256_bytes(runtime_code.encode("utf-8")),
    }

    package_report = {
        "schemaVersion": 1,
        "status": "passed",
        "root": str(root),
        "entrypoint": entrypoint_path,
        "fileCount": len(files),
        "totalSourceBytes": sum(file.size_bytes for file in files),
        "sourceTreeSha256": manifest["sourceTreeSha256"],
        "runtimeSha256": manifest["runtimeSha256"],
        "limits": {
            "maxFileBytes": max_file_bytes,
            "maxTotalBytes": max_total_bytes,
        },
    }
    return ProjectPackage(
        manifest=manifest,
        files=files,
        runtime_code=runtime_code,
        package_report=package_report,
    )


def extract_project_from_runtime(code: str) -> tuple[dict[str, Any], list[ProjectFile]]:
    if GENERATED_HEADER not in code:
        raise ProjectSyncError("Python item was not generated by sync-python-project")
    manifest = _extract_constant_json(code, "__NARADA_WORKBENCH_SOURCE_MANIFEST__")
    if manifest.get("generator") != PROJECT_SYNC_GENERATOR:
        raise ProjectSyncError("Python item was not generated by sync-python-project")
    bundle_encoded = _extract_constant_json(code, "__NARADA_WORKBENCH_SOURCE_BUNDLE__")
    if not isinstance(bundle_encoded, str) or not bundle_encoded:
        raise ProjectSyncError("Generated runtime did not contain source bundle")
    try:
        raw = gzip.decompress(base64.b64decode(bundle_encoded.encode("ascii")))
        bundle = json.loads(raw.decode("utf-8"))
    except Exception as exc:
        raise ProjectSyncError(
            "Generated runtime source bundle could not be decoded"
        ) from exc
    rows = bundle.get("files")
    if not isinstance(rows, list):
        raise ProjectSyncError("Generated runtime source bundle did not contain files")
    files: list[ProjectFile] = []
    for row in rows:
        if not isinstance(row, dict):
            raise ProjectSyncError("Generated runtime source bundle row was invalid")
        relative_path = row.get("path")
        content = row.get("content")
        if not isinstance(relative_path, str) or not isinstance(content, str):
            raise ProjectSyncError("Generated runtime source file row was invalid")
        normalized = _normalize_relative_path(relative_path)
        content_bytes = content.encode("utf-8")
        files.append(
            ProjectFile(
                relative_path=normalized,
                content=content,
                content_bytes=content_bytes,
                sha256=_sha256_bytes(content_bytes),
                size_bytes=len(content_bytes),
            )
        )
    _validate_manifest_matches_files(manifest, files)
    manifest = {**manifest, "runtimeSha256": _sha256_bytes(code.encode("utf-8"))}
    return manifest, sorted(files, key=lambda file: file.relative_path)


def scan_project_package_findings(package: ProjectPackage) -> dict[str, list[str]]:
    failures: list[str] = []
    taints: list[str] = []
    for file in package.files:
        for index, pattern in enumerate(_SECRET_PATTERNS, start=1):
            if pattern.search(file.content):
                failures.append(f"secret-pattern-{index}:{file.relative_path}")
        for index, pattern in enumerate(_STATIC_ANSWER_PATTERNS, start=1):
            if pattern.search(file.content) or pattern.search(file.relative_path):
                failures.append(f"static-answer-pattern-{index}:{file.relative_path}")
        for index, pattern in enumerate(_SELF_REVIEW_PATTERNS, start=1):
            if pattern.search(file.content):
                taints.append(f"self-review-pattern-{index}:{file.relative_path}")
    return {"failures": failures, "taints": taints}


def diff_project_package(
    *,
    local_package: ProjectPackage,
    remote_manifest: dict[str, Any],
) -> dict[str, Any]:
    local_files = {
        str(row["path"]): row["sha256"] for row in local_package.manifest["files"]
    }
    remote_files = {
        str(row["path"]): row["sha256"] for row in remote_manifest.get("files") or []
    }
    added = sorted(set(local_files) - set(remote_files))
    deleted = sorted(set(remote_files) - set(local_files))
    modified = sorted(
        path
        for path in set(local_files).intersection(remote_files)
        if local_files[path] != remote_files[path]
    )
    matches = not added and not deleted and not modified
    status = "passed" if matches else "needs_review"
    return {
        "schemaVersion": 1,
        "status": status,
        "matches": matches,
        "localSourceTreeSha256": local_package.manifest["sourceTreeSha256"],
        "remoteSourceTreeSha256": remote_manifest.get("sourceTreeSha256"),
        "entrypointMatches": local_package.manifest["entrypoint"]
        == remote_manifest.get("entrypoint"),
        "added": added,
        "deleted": deleted,
        "modified": modified,
    }


def write_exported_project(
    *,
    out: str | Path,
    files: list[ProjectFile],
    allow_overwrite: bool = False,
) -> list[dict[str, Any]]:
    root = Path(out)
    if root.exists() and any(root.iterdir()) and not allow_overwrite:
        raise ProjectSyncError(
            "Export output directory already exists and is not empty; choose a new --out path"
        )
    root.mkdir(parents=True, exist_ok=True)
    resolved_root = root.resolve()
    exported: list[dict[str, Any]] = []
    for file in files:
        relative_path = _normalize_relative_path(file.relative_path)
        target = root / relative_path
        resolved = target.resolve()
        if not resolved.is_relative_to(resolved_root):
            raise ProjectSyncError("Generated runtime attempted to export path escape")
        if target.exists() and not allow_overwrite:
            raise ProjectSyncError(
                f"Export would overwrite existing file: {relative_path}"
            )
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(file.content, encoding="utf-8")
        exported.append(
            {
                "path": relative_path,
                "sha256": file.sha256,
                "sizeBytes": file.size_bytes,
            }
        )
    return exported


def _scan_project(
    root: Path,
    *,
    max_file_bytes: int,
    max_total_bytes: int,
) -> list[ProjectFile]:
    files: list[ProjectFile] = []
    total_bytes = 0
    for path in sorted(root.rglob("*")):
        relative = path.relative_to(root)
        if _is_excluded_path(relative):
            continue
        if path.is_symlink():
            raise ProjectSyncError(f"Symlinks are not supported: {relative.as_posix()}")
        if path.is_dir():
            continue
        relative_path = _normalize_relative_path(relative.as_posix())
        if Path(relative_path).name.startswith("."):
            raise ProjectSyncError(f"Hidden files are not supported: {relative_path}")
        if path.name in EXCLUDED_FILE_NAMES:
            continue
        if path.suffix.lower() not in ALLOWED_SUFFIXES:
            raise ProjectSyncError(
                f"Unsupported project file extension for {relative_path}"
            )
        if path.name.startswith("generated-runtime"):
            raise ProjectSyncError(
                f"Generated runtime files are not supported as source: {relative_path}"
            )
        data = path.read_bytes()
        if len(data) > max_file_bytes:
            raise ProjectSyncError(f"Project file exceeds size limit: {relative_path}")
        total_bytes += len(data)
        if total_bytes > max_total_bytes:
            raise ProjectSyncError("Project source bundle exceeds total size limit")
        if b"\x00" in data:
            raise ProjectSyncError(
                f"Binary project files are not supported: {relative_path}"
            )
        try:
            content = data.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise ProjectSyncError(
                f"Project file is not valid UTF-8: {relative_path}"
            ) from exc
        files.append(
            ProjectFile(
                relative_path=relative_path,
                content=content,
                content_bytes=data,
                sha256=_sha256_bytes(data),
                size_bytes=len(data),
            )
        )
    if not files:
        raise ProjectSyncError("Project did not contain any supported source files")
    return files


def _is_excluded_path(relative: Path) -> bool:
    parts = relative.parts
    return any(part in EXCLUDED_DIR_NAMES for part in parts)


def _normalize_relative_path(value: str) -> str:
    if os.path.isabs(value):
        raise ProjectSyncError("Project paths must be relative")
    pure = PurePosixPath(value)
    parts = pure.parts
    if not parts or any(part in {"", ".", ".."} for part in parts):
        raise ProjectSyncError(
            "Project paths must not contain empty or parent segments"
        )
    return pure.as_posix()


def _source_tree_hash(files: list[ProjectFile]) -> str:
    return _sha256_json(
        [
            {
                "path": file.relative_path,
                "sha256": file.sha256,
                "sizeBytes": file.size_bytes,
            }
            for file in sorted(files, key=lambda current: current.relative_path)
        ]
    )


def _validate_manifest_matches_files(
    manifest: dict[str, Any], files: list[ProjectFile]
) -> None:
    expected_files = {
        str(row.get("path")): row
        for row in manifest.get("files") or []
        if isinstance(row, dict)
    }
    if set(expected_files) != {file.relative_path for file in files}:
        raise ProjectSyncError("Generated runtime manifest files did not match bundle")
    for file in files:
        row = expected_files[file.relative_path]
        if row.get("sha256") != file.sha256 or row.get("sizeBytes") != file.size_bytes:
            raise ProjectSyncError(
                f"Generated runtime manifest hash mismatch for {file.relative_path}"
            )
    if manifest.get("sourceTreeSha256") != _source_tree_hash(files):
        raise ProjectSyncError("Generated runtime source tree hash mismatch")


def _render_runtime_code(manifest: dict[str, Any], encoded_bundle: str) -> str:
    manifest_json = json.dumps(manifest, indent=2, sort_keys=True)
    manifest_string = json.dumps(manifest_json)
    bundle_json = json.dumps(encoded_bundle)
    return f"""# {GENERATED_HEADER}
# Source generator: {PROJECT_SYNC_GENERATOR}

import base64
import gzip
import json
import os
import runpy
import sys
import tempfile
from pathlib import Path

__NARADA_WORKBENCH_SOURCE_MANIFEST__ = json.loads({manifest_string})
__NARADA_WORKBENCH_SOURCE_BUNDLE__ = {bundle_json}


def __narada_workbench_bootstrap__() -> None:
    bundle = json.loads(
        gzip.decompress(
            base64.b64decode(__NARADA_WORKBENCH_SOURCE_BUNDLE__.encode("ascii"))
        ).decode("utf-8")
    )
    runtime_root = Path(tempfile.mkdtemp(prefix="narada_project_sync_"))
    for source_file in bundle["files"]:
        relative_path = Path(source_file["path"])
        target = runtime_root / relative_path
        resolved = target.resolve()
        if os.path.commonpath([str(runtime_root.resolve()), str(resolved)]) != str(runtime_root.resolve()):
            raise RuntimeError("Generated project bundle attempted path escape")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(source_file["content"], encoding="utf-8")
    sys.path.insert(0, str(runtime_root))
    runpy.run_path(
        str(runtime_root / __NARADA_WORKBENCH_SOURCE_MANIFEST__["entrypoint"]),
        init_globals=globals(),
        run_name="__main__",
    )


__narada_workbench_bootstrap__()
"""


def _extract_constant_json(code: str, name: str) -> Any:
    try:
        module = ast.parse(code)
    except SyntaxError as exc:
        raise ProjectSyncError("Generated runtime was not valid Python") from exc
    for node in module.body:
        if not isinstance(node, ast.Assign):
            continue
        if not any(
            isinstance(target, ast.Name) and target.id == name
            for target in node.targets
        ):
            continue
        value = node.value
        if isinstance(value, ast.Constant) and isinstance(value.value, str):
            if name.endswith("BUNDLE__"):
                return value.value
            return json.loads(value.value)
        if (
            isinstance(value, ast.Call)
            and isinstance(value.func, ast.Attribute)
            and value.func.attr == "loads"
            and len(value.args) == 1
            and isinstance(value.args[0], ast.Constant)
            and isinstance(value.args[0].value, str)
        ):
            return json.loads(value.args[0].value)
    raise ProjectSyncError(f"Generated runtime did not contain {name}")


def _now_iso() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


__all__ = [
    "GENERATED_HEADER",
    "PROJECT_SYNC_GENERATOR",
    "ProjectPackage",
    "ProjectSyncError",
    "build_project_package",
    "diff_project_package",
    "extract_project_from_runtime",
    "scan_project_package_findings",
    "write_exported_project",
]
